name: valltest
services:
  # Сервис NestJS приложения
  app:
    container_name: valltest-backend-app
    image: dwaru/valltest-backend-app:${VALLTEST_VERSION}
    ports:
      - "7777:${PORT}" # Пробрасывает порт 7777 из контейнера на хост-машину
    environment:
      SERVER: ${SERVER}
      PORT: ${PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_SYNCHRONIZE: ${DATABASE_SYNCHRONIZE}
    depends_on:
      - db # Указывает, что сервис app зависит от сервиса db
    networks:
      - valltest-network

  # Сервис базы данных PostgreSQL
  db:
    container_name: postgres-db
    image: postgres:${POSTGRES_VERSION} # Использует образ PostgreSQL версии 16
    ports:
      - "5432:${DATABASE_PORT}" # Пробрасывает порт 5432 из контейнера на хост-машину (для отладки)
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: on-failure
    volumes:
      - db_data:/var/lib/postgresql/data # Монтирует том для хранения данных
    networks:
      - valltest-network

# Определяем том для хранения данных базы данных
volumes:
  db_data:


networks:
  valltest-network:
